Repository GuilhermeFFe/IoT-sistema-refrigeracao, pull requests merged in 2020-11, with the labels that each got.

#1 Adicionando .idea no .gitignore
  .gitignore
Labels: Internal

#3 Create ESP32.ino
  ESP32.ino
Labels: enhancement

#4 Criando plano de trabalho
  docs/cronograma.pdf
  docs/plano_de_trabalho.md
Labels: documentation
